"""add_stego_jobs_table

Revision ID: b70aee728a0a
Revises: 79f1ce8355f2
Create Date: 2025-12-09 07:22:54.810610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70aee728a0a'
down_revision = '79f1ce8355f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stego_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.Enum('EMBED', 'EXTRACT', name='operationtype'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROGRESS', 'SUCCESS', 'FAILURE', name='jobstatus'), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stego_jobs_id'), 'stego_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_stego_jobs_job_id'), 'stego_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_stego_jobs_user_id'), 'stego_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stego_jobs_user_id'), table_name='stego_jobs')
    op.drop_index(op.f('ix_stego_jobs_job_id'), table_name='stego_jobs')
    op.drop_index(op.f('ix_stego_jobs_id'), table_name='stego_jobs')
    op.drop_table('stego_jobs')
    # ### end Alembic commands ###

